version: '3.8'
services:
  postgres-gorm:
    image: postgres:13
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    networks:
      - postgres-gorm-network

networks:
  postgres-gorm-network:
    driver: bridge